[project]
name = "python_2025_20"
version = "0.1.0"
description = "test project"
readme = "readme.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "pydantic",
    "uvicorn",
    "transformers",
    "torch",
]
